baseurl = "http://www.build.naomilago.netlify.com"
defaultcontentlanguage = "en"
disqusShortname = "yourdiscussshortname"
languagecode = "en"
paginate = 20
pygmentsUseClasses = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "coder-portfolio"
title = "Naomi Lago"
[languages.en]
languagename = "English"
title = "Naomi Lago"
[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 1
[[languages.en.menu.main]]
name = "Blog"
url = "posts"
weight = 2
[languages.en.params]
author = "Naomi Lago"
description = "Naomi Lago's personal blog"
fixedbarContent = "Do you want to know me more private? → "
fixedbarContentAfter = "Thank You! Please share it if you like it → "
footercontent = "Enter a text here."
info = "Trans woman && Technology Lover"
keywords = "blog,developer,personal,transgender,technology,career"
[languages.pt]
languagename = "Português"
title = "Naomi Lago"
[[languages.pt.menu.main]]
name = "Sobre"
url = "about"
weight = 1
[[languages.pt.menu.main]]
name = "Blog"
url = "posts"
weight = 2
[languages.pt.params]
author = "Naomi Lago"
description = "Blog pessoal da Naomi Lago"
fixedbarContent = "Quer me conhecer mais de perto? → "
fixedbarContentAfter = "Obrigada! Não se esqueça de compartilhar se você gostar → "
footercontent = "Insira um texto aqui."
info = "Mulher Trans && Amante de Tecnologia"
keywords = "blog,desenvolvimento,trans,tecnologia,carreira"
[[menu.main]]
name = "Blog"
url = "posts"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[params]
author = "Naomi Lago"
avatarurl = "images/avatar.png"
custom_css = []
description = "Naomi Lago's personal blog"
enableFacebookShare = true
enableHatenaShare = true
enableLineShare = true
enableLinkedInShare = true
enableTwitterShare = true
fixedbarContent = "Do you want to know me more private?→"
fixedbarContentAfter = "Thank You! Please share it if you like it→"
footercontent = "Enter a text here."
hideCopyright = false
hideCredits = false
info = "Trans woman && Technology Lover"
itemscentered = true
keywords = "blog,development,personal,transgender,technology,career"
langseparator = "|"
rtl = false
snsShare = true
thumbnail = "/uploads/screenshot.png"
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/naomilag0/"
weight = 1
[[params.social]]
icon = "fab fa-linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/naomilag0/"
weight = 2
[[params.social]]
icon = "fab fa-telegram"
name = "Telegram"
url = "https://www.t.me/naomilag0/"
weight = 3
[[params.social]]
icon = "fab fa-facebook"
name = "Facebook"
url = "https://facebook.com/naomilag0/"
weight = 4
[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/naomilag0/"
weight = 5
